package codepages

import (
	. "github.com/magicmonty/wbxml-go/wbxml"
)

const (
	NS_DOCUMENT_LIBRARY                   string = "DocumentLibrary"
	TAG_DOCUMENT_LIBRARY_LINKID           string = "LinkId"
	TAG_DOCUMENT_LIBRARY_DISPLAYNAME      string = "DisplayName"
	TAG_DOCUMENT_LIBRARY_ISFOLDER         string = "IsFolder"
	TAG_DOCUMENT_LIBRARY_CREATIONDATE     string = "CreationDate"
	TAG_DOCUMENT_LIBRARY_LASTMODIFIEDDATE string = "LastModifiedDate"
	TAG_DOCUMENT_LIBRARY_ISHIDDEN         string = "IsHidden"
	TAG_DOCUMENT_LIBRARY_CONTENTLENGTH    string = "ContentLength"
	TAG_DOCUMENT_LIBRARY_CONTENTTYPE      string = "ContentType"
)

const (
	CP_DOCUMENT_LIBRARY                  byte = 19
	ID_DOCUMENT_LIBRARY_LINKID           byte = 0x05
	ID_DOCUMENT_LIBRARY_DISPLAYNAME      byte = 0x06
	ID_DOCUMENT_LIBRARY_ISFOLDER         byte = 0x07
	ID_DOCUMENT_LIBRARY_CREATIONDATE     byte = 0x08
	ID_DOCUMENT_LIBRARY_LASTMODIFIEDDATE byte = 0x09
	ID_DOCUMENT_LIBRARY_ISHIDDEN         byte = 0x0A
	ID_DOCUMENT_LIBRARY_CONTENTLENGTH    byte = 0x0B
	ID_DOCUMENT_LIBRARY_CONTENTTYPE      byte = 0x0C
)

func DocumentLibrary() CodePage {
	result := NewCodePage(NS_DOCUMENT_LIBRARY, CP_DOCUMENT_LIBRARY)

	result.AddTag(TAG_DOCUMENT_LIBRARY_LINKID, ID_DOCUMENT_LIBRARY_LINKID)
	result.AddTag(TAG_DOCUMENT_LIBRARY_DISPLAYNAME, ID_DOCUMENT_LIBRARY_DISPLAYNAME)
	result.AddTag(TAG_DOCUMENT_LIBRARY_ISFOLDER, ID_DOCUMENT_LIBRARY_ISFOLDER)
	result.AddTag(TAG_DOCUMENT_LIBRARY_CREATIONDATE, ID_DOCUMENT_LIBRARY_CREATIONDATE)
	result.AddTag(TAG_DOCUMENT_LIBRARY_LASTMODIFIEDDATE, ID_DOCUMENT_LIBRARY_LASTMODIFIEDDATE)
	result.AddTag(TAG_DOCUMENT_LIBRARY_ISHIDDEN, ID_DOCUMENT_LIBRARY_ISHIDDEN)
	result.AddTag(TAG_DOCUMENT_LIBRARY_CONTENTLENGTH, ID_DOCUMENT_LIBRARY_CONTENTLENGTH)
	result.AddTag(TAG_DOCUMENT_LIBRARY_CONTENTTYPE, ID_DOCUMENT_LIBRARY_CONTENTTYPE)

	return result
}
