package codepages

import (
	"testing"
)

func Test_DocumentLibrary(t *testing.T) {
	cp := DocumentLibrary()
	checkTagCount(t, 8, cp)
	checkTagExists(t, TAG_DOCUMENT_LIBRARY_LINKID, ID_DOCUMENT_LIBRARY_LINKID, cp)
	checkTagExists(t, TAG_DOCUMENT_LIBRARY_DISPLAYNAME, ID_DOCUMENT_LIBRARY_DISPLAYNAME, cp)
	checkTagExists(t, TAG_DOCUMENT_LIBRARY_ISFOLDER, ID_DOCUMENT_LIBRARY_ISFOLDER, cp)
	checkTagExists(t, TAG_DOCUMENT_LIBRARY_CREATIONDATE, ID_DOCUMENT_LIBRARY_CREATIONDATE, cp)
	checkTagExists(t, TAG_DOCUMENT_LIBRARY_LASTMODIFIEDDATE, ID_DOCUMENT_LIBRARY_LASTMODIFIEDDATE, cp)
	checkTagExists(t, TAG_DOCUMENT_LIBRARY_ISHIDDEN, ID_DOCUMENT_LIBRARY_ISHIDDEN, cp)
	checkTagExists(t, TAG_DOCUMENT_LIBRARY_CONTENTLENGTH, ID_DOCUMENT_LIBRARY_CONTENTLENGTH, cp)
	checkTagExists(t, TAG_DOCUMENT_LIBRARY_CONTENTTYPE, ID_DOCUMENT_LIBRARY_CONTENTTYPE, cp)
}
