package codepages

import (
	"testing"
)

func Test_FolderHierarchy(t *testing.T) {
	cp := FolderHierarchy()
	checkTagCount(t, 15, cp)

	checkTagExists(t, TAG_FOLDER_HIERARCHY_DISPLAYNAME, ID_FOLDER_HIERARCHY_DISPLAYNAME, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_SERVERID, ID_FOLDER_HIERARCHY_SERVERID, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_PARENTID, ID_FOLDER_HIERARCHY_PARENTID, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_TYPE, ID_FOLDER_HIERARCHY_TYPE, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_STATUS, ID_FOLDER_HIERARCHY_STATUS, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_CHANGES, ID_FOLDER_HIERARCHY_CHANGES, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_ADD, ID_FOLDER_HIERARCHY_ADD, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_DELETE, ID_FOLDER_HIERARCHY_DELETE, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_UPDATE, ID_FOLDER_HIERARCHY_UPDATE, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_SYNCKEY, ID_FOLDER_HIERARCHY_SYNCKEY, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_FOLDERCREATE, ID_FOLDER_HIERARCHY_FOLDERCREATE, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_FOLDERDELETE, ID_FOLDER_HIERARCHY_FOLDERDELETE, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_FOLDERUPDATE, ID_FOLDER_HIERARCHY_FOLDERUPDATE, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_FOLDERSYNC, ID_FOLDER_HIERARCHY_FOLDERSYNC, cp)
	checkTagExists(t, TAG_FOLDER_HIERARCHY_COUNT, ID_FOLDER_HIERARCHY_COUNT, cp)
}
