package codepages

import (
	. "github.com/magicmonty/wbxml-go/wbxml"
)

const (
	NS_FOLDER_HIERARCHY               string = "FolderHierarchy"
	TAG_FOLDER_HIERARCHY_DISPLAYNAME  string = "DisplayName"
	TAG_FOLDER_HIERARCHY_SERVERID     string = "ServerId"
	TAG_FOLDER_HIERARCHY_PARENTID     string = "ParentId"
	TAG_FOLDER_HIERARCHY_TYPE         string = "Type"
	TAG_FOLDER_HIERARCHY_STATUS       string = "Status"
	TAG_FOLDER_HIERARCHY_CHANGES      string = "Changes"
	TAG_FOLDER_HIERARCHY_ADD          string = "Add"
	TAG_FOLDER_HIERARCHY_DELETE       string = "Delete"
	TAG_FOLDER_HIERARCHY_UPDATE       string = "Update"
	TAG_FOLDER_HIERARCHY_SYNCKEY      string = "SyncKey"
	TAG_FOLDER_HIERARCHY_FOLDERCREATE string = "FolderCreate"
	TAG_FOLDER_HIERARCHY_FOLDERDELETE string = "FolderDelete"
	TAG_FOLDER_HIERARCHY_FOLDERUPDATE string = "FolderUpdate"
	TAG_FOLDER_HIERARCHY_FOLDERSYNC   string = "FolderSync"
	TAG_FOLDER_HIERARCHY_COUNT        string = "Count"
)

const (
	CP_FOLDER_HIERARCHY              byte = 7
	ID_FOLDER_HIERARCHY_DISPLAYNAME  byte = 0x07
	ID_FOLDER_HIERARCHY_SERVERID     byte = 0x08
	ID_FOLDER_HIERARCHY_PARENTID     byte = 0x09
	ID_FOLDER_HIERARCHY_TYPE         byte = 0x0A
	ID_FOLDER_HIERARCHY_STATUS       byte = 0x0C
	ID_FOLDER_HIERARCHY_CHANGES      byte = 0x0E
	ID_FOLDER_HIERARCHY_ADD          byte = 0x0F
	ID_FOLDER_HIERARCHY_DELETE       byte = 0x10
	ID_FOLDER_HIERARCHY_UPDATE       byte = 0x11
	ID_FOLDER_HIERARCHY_SYNCKEY      byte = 0x12
	ID_FOLDER_HIERARCHY_FOLDERCREATE byte = 0x13
	ID_FOLDER_HIERARCHY_FOLDERDELETE byte = 0x14
	ID_FOLDER_HIERARCHY_FOLDERUPDATE byte = 0x15
	ID_FOLDER_HIERARCHY_FOLDERSYNC   byte = 0x16
	ID_FOLDER_HIERARCHY_COUNT        byte = 0x17
)

func FolderHierarchy() CodePage {
	result := NewCodePage(NS_FOLDER_HIERARCHY, CP_FOLDER_HIERARCHY)

	result.AddTag(TAG_FOLDER_HIERARCHY_DISPLAYNAME, ID_FOLDER_HIERARCHY_DISPLAYNAME)
	result.AddTag(TAG_FOLDER_HIERARCHY_SERVERID, ID_FOLDER_HIERARCHY_SERVERID)
	result.AddTag(TAG_FOLDER_HIERARCHY_PARENTID, ID_FOLDER_HIERARCHY_PARENTID)
	result.AddTag(TAG_FOLDER_HIERARCHY_TYPE, ID_FOLDER_HIERARCHY_TYPE)
	result.AddTag(TAG_FOLDER_HIERARCHY_STATUS, ID_FOLDER_HIERARCHY_STATUS)
	result.AddTag(TAG_FOLDER_HIERARCHY_CHANGES, ID_FOLDER_HIERARCHY_CHANGES)
	result.AddTag(TAG_FOLDER_HIERARCHY_ADD, ID_FOLDER_HIERARCHY_ADD)
	result.AddTag(TAG_FOLDER_HIERARCHY_DELETE, ID_FOLDER_HIERARCHY_DELETE)
	result.AddTag(TAG_FOLDER_HIERARCHY_UPDATE, ID_FOLDER_HIERARCHY_UPDATE)
	result.AddTag(TAG_FOLDER_HIERARCHY_SYNCKEY, ID_FOLDER_HIERARCHY_SYNCKEY)
	result.AddTag(TAG_FOLDER_HIERARCHY_FOLDERCREATE, ID_FOLDER_HIERARCHY_FOLDERCREATE)
	result.AddTag(TAG_FOLDER_HIERARCHY_FOLDERDELETE, ID_FOLDER_HIERARCHY_FOLDERDELETE)
	result.AddTag(TAG_FOLDER_HIERARCHY_FOLDERUPDATE, ID_FOLDER_HIERARCHY_FOLDERUPDATE)
	result.AddTag(TAG_FOLDER_HIERARCHY_FOLDERSYNC, ID_FOLDER_HIERARCHY_FOLDERSYNC)
	result.AddTag(TAG_FOLDER_HIERARCHY_COUNT, ID_FOLDER_HIERARCHY_COUNT)

	return result
}
