package codepages

import (
	"testing"
)

func Test_MeetingResponse(t *testing.T) {
	cp := MeetingResponse()
	checkTagCount(t, 9, cp)

	checkTagExists(t, TAG_MEETING_RESPONSE_CALENDARID, ID_MEETING_RESPONSE_CALENDARID, cp)
	checkTagExists(t, TAG_MEETING_RESPONSE_COLLECTIONID, ID_MEETING_RESPONSE_COLLECTIONID, cp)
	checkTagExists(t, TAG_MEETING_RESPONSE_MEETINGRESPONSE, ID_MEETING_RESPONSE_MEETINGRESPONSE, cp)
	checkTagExists(t, TAG_MEETING_RESPONSE_REQUESTID, ID_MEETING_RESPONSE_REQUESTID, cp)
	checkTagExists(t, TAG_MEETING_RESPONSE_REQUEST, ID_MEETING_RESPONSE_REQUEST, cp)
	checkTagExists(t, TAG_MEETING_RESPONSE_RESULT, ID_MEETING_RESPONSE_RESULT, cp)
	checkTagExists(t, TAG_MEETING_RESPONSE_STATUS, ID_MEETING_RESPONSE_STATUS, cp)
	checkTagExists(t, TAG_MEETING_RESPONSE_USERRESPONSE, ID_MEETING_RESPONSE_USERRESPONSE, cp)
	checkTagExists(t, TAG_MEETING_RESPONSE_INSTANCEID, ID_MEETING_RESPONSE_INSTANCEID, cp)
}
