package codepages

import (
	. "github.com/magicmonty/wbxml-go/wbxml"
)

func Provision() CodePage {
	result := NewCodePage("Provision", 14)

	result.AddTag("Provision", 0x05)
	result.AddTag("Policies", 0x06)
	result.AddTag("Policy", 0x07)
	result.AddTag("PolicyType", 0x08)
	result.AddTag("PolicyKey", 0x09)
	result.AddTag("Data", 0x0A)
	result.AddTag("Status", 0x0B)
	result.AddTag("RemoteWipe", 0x0C)
	result.AddTag("EASProvisionDoc", 0x0D)
	result.AddTag("DevicePasswordEnabled", 0x0E)
	result.AddTag("AlphanumericDevicePasswordRequired", 0x0F)
	result.AddTag("DeviceEncryptionEnabled", 0x10)
	result.AddTag("RequireStorageCardEncryption", 0x10) // equivalent to DeviceEncryptionEnabled
	result.AddTag("PasswordRecoveryEnabled", 0x11)
	result.AddTag("AttachmentsEnabled", 0x13)
	result.AddTag("MinDevicePasswordLength", 0x14)
	result.AddTag("MaxInactivityTimeDeviceLock", 0x15)
	result.AddTag("MaxDevicePasswordFailedAttempts", 0x16)
	result.AddTag("MaxAttachmentSize", 0x17)
	result.AddTag("AllowSimpleDevicePassword", 0x18)
	result.AddTag("DevicePasswordExpiration", 0x19)
	result.AddTag("DevicePasswordHistory", 0x1A)
	result.AddTag("AllowStorageCard", 0x1B)
	result.AddTag("AllowCamera", 0x1C)
	result.AddTag("RequireDeviceEncryption", 0x1D)
	result.AddTag("AllowUnsignedApplications", 0x1E)
	result.AddTag("AllowUnsignedInstallationPackages", 0x1F)
	result.AddTag("MinDevicePasswordComplexCharacters", 0x20)
	result.AddTag("AllowWiFi", 0x21)
	result.AddTag("AllowTextMessaging", 0x22)
	result.AddTag("AllowPOPIMAPEmail", 0x23)
	result.AddTag("AllowBluetooth", 0x24)
	result.AddTag("AllowIrDA", 0x25)
	result.AddTag("RequireManualSyncWhenRoaming", 0x26)
	result.AddTag("AllowDesktopSync", 0x27)
	result.AddTag("MaxCalendarAgeFilter", 0x28)
	result.AddTag("AllowHTMLEmail", 0x29)
	result.AddTag("MaxEmailAgeFilter", 0x2A)
	result.AddTag("MaxEmailBodyTruncationSize", 0x2B)
	result.AddTag("MaxEmailHTMLBodyTruncationSize", 0x2C)
	result.AddTag("RequireSignedSMIMEMessages", 0x2D)
	result.AddTag("RequireEncryptedSMIMEMessages", 0x2E)
	result.AddTag("RequireSignedSMIMEAlgorithm", 0x2F)
	result.AddTag("RequireEncryptionSMIMEAlgorithm", 0x30)
	result.AddTag("AllowSMIMEEncryptionAlgorithmNegotiation", 0x31)
	result.AddTag("AllowSMIMESoftCerts", 0x32)
	result.AddTag("AllowBrowser", 0x33)
	result.AddTag("AllowConsumerEmail", 0x34)
	result.AddTag("AllowRemoteDesktop", 0x35)
	result.AddTag("AllowInternetSharing", 0x36)
	result.AddTag("UnapprovedInROMApplicationList", 0x37)
	result.AddTag("ApplicationName", 0x38)
	result.AddTag("ApprovedApplicationList", 0x39)
	result.AddTag("Hash", 0x3A)

	return result
}
