package codepages

import (
	. "github.com/magicmonty/activesync-go/activesync/base"
	. "github.com/magicmonty/wbxml-go/wbxml"
)

const (
	NS_RIGHTS_MANAGEMENT                                     string = "RightsManagement"
	TAG_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTSUPPORT            string = "RightsManagementSupport"
	TAG_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTTEMPLATES          string = "RightsManagementTemplates"
	TAG_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTTEMPLATE           string = "RightsManagementTemplate"
	TAG_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTLICENSE            string = "RightsManagementLicense"
	TAG_RIGHTS_MANAGEMENT_EDITALLOWED                        string = "EditAllowed"
	TAG_RIGHTS_MANAGEMENT_REPLYALLOWED                       string = "ReplyAllowed"
	TAG_RIGHTS_MANAGEMENT_REPLYALLALLOWED                    string = "ReplyAllAllowed"
	TAG_RIGHTS_MANAGEMENT_FORWARDALLOWED                     string = "ForwardAllowed"
	TAG_RIGHTS_MANAGEMENT_MODIFYRECIPIENTSALLOWED            string = "ModifyRecipientsAllowed"
	TAG_RIGHTS_MANAGEMENT_EXTRACTALLOWED                     string = "ExtractAllowed"
	TAG_RIGHTS_MANAGEMENT_PRINTALLOWED                       string = "PrintAllowed"
	TAG_RIGHTS_MANAGEMENT_EXPORTALLOWED                      string = "ExportAllowed"
	TAG_RIGHTS_MANAGEMENT_PROGRAMMATICACCESSALLOWED          string = "ProgrammaticAccessAllowed"
	TAG_RIGHTS_MANAGEMENT_OWNER                              string = "Owner"
	TAG_RIGHTS_MANAGEMENT_CONTENTEXPIRYDATE                  string = "ContentExpiryDate"
	TAG_RIGHTS_MANAGEMENT_TEMPLATEID                         string = "TemplateID"
	TAG_RIGHTS_MANAGEMENT_TEMPLATENAME                       string = "TemplateName"
	TAG_RIGHTS_MANAGEMENT_TEMPLATEDESCRIPTION                string = "TemplateDescription"
	TAG_RIGHTS_MANAGEMENT_CONTENTOWNER                       string = "ContentOwner"
	TAG_RIGHTS_MANAGEMENT_REMOVERIGHTSMANAGEMENTDISTRIBUTION string = "RemoveRightsManagementDistribution"
)

const (
	CP_RIGHTS_MANAGEMENT                                    byte = 24
	ID_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTSUPPORT            byte = 0x05
	ID_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTTEMPLATES          byte = 0x06
	ID_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTTEMPLATE           byte = 0x07
	ID_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTLICENSE            byte = 0x08
	ID_RIGHTS_MANAGEMENT_EDITALLOWED                        byte = 0x09
	ID_RIGHTS_MANAGEMENT_REPLYALLOWED                       byte = 0x0A
	ID_RIGHTS_MANAGEMENT_REPLYALLALLOWED                    byte = 0x0B
	ID_RIGHTS_MANAGEMENT_FORWARDALLOWED                     byte = 0x0C
	ID_RIGHTS_MANAGEMENT_MODIFYRECIPIENTSALLOWED            byte = 0x0D
	ID_RIGHTS_MANAGEMENT_EXTRACTALLOWED                     byte = 0x0E
	ID_RIGHTS_MANAGEMENT_PRINTALLOWED                       byte = 0x0F
	ID_RIGHTS_MANAGEMENT_EXPORTALLOWED                      byte = 0x10
	ID_RIGHTS_MANAGEMENT_PROGRAMMATICACCESSALLOWED          byte = 0x11
	ID_RIGHTS_MANAGEMENT_OWNER                              byte = 0x12
	ID_RIGHTS_MANAGEMENT_CONTENTEXPIRYDATE                  byte = 0x13
	ID_RIGHTS_MANAGEMENT_TEMPLATEID                         byte = 0x14
	ID_RIGHTS_MANAGEMENT_TEMPLATENAME                       byte = 0x15
	ID_RIGHTS_MANAGEMENT_TEMPLATEDESCRIPTION                byte = 0x16
	ID_RIGHTS_MANAGEMENT_CONTENTOWNER                       byte = 0x17
	ID_RIGHTS_MANAGEMENT_REMOVERIGHTSMANAGEMENTDISTRIBUTION byte = 0x18
)

// not supported with MS-ASProtocolVersion 12.1 or 14.0
func RightsManagement(protocolVersion byte) CodePage {
	result := NewCodePage(NS_RIGHTS_MANAGEMENT, CP_RIGHTS_MANAGEMENT)

	if protocolVersion > PROTOCOL_VERSION_14_0 {
		result.AddTag(TAG_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTSUPPORT, ID_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTSUPPORT)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTTEMPLATES, ID_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTTEMPLATES)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTTEMPLATE, ID_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTTEMPLATE)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTLICENSE, ID_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTLICENSE)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_EDITALLOWED, ID_RIGHTS_MANAGEMENT_EDITALLOWED)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_REPLYALLOWED, ID_RIGHTS_MANAGEMENT_REPLYALLOWED)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_REPLYALLALLOWED, ID_RIGHTS_MANAGEMENT_REPLYALLALLOWED)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_FORWARDALLOWED, ID_RIGHTS_MANAGEMENT_FORWARDALLOWED)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_MODIFYRECIPIENTSALLOWED, ID_RIGHTS_MANAGEMENT_MODIFYRECIPIENTSALLOWED)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_EXTRACTALLOWED, ID_RIGHTS_MANAGEMENT_EXTRACTALLOWED)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_PRINTALLOWED, ID_RIGHTS_MANAGEMENT_PRINTALLOWED)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_EXPORTALLOWED, ID_RIGHTS_MANAGEMENT_EXPORTALLOWED)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_PROGRAMMATICACCESSALLOWED, ID_RIGHTS_MANAGEMENT_PROGRAMMATICACCESSALLOWED)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_OWNER, ID_RIGHTS_MANAGEMENT_OWNER)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_CONTENTEXPIRYDATE, ID_RIGHTS_MANAGEMENT_CONTENTEXPIRYDATE)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_TEMPLATEID, ID_RIGHTS_MANAGEMENT_TEMPLATEID)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_TEMPLATENAME, ID_RIGHTS_MANAGEMENT_TEMPLATENAME)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_TEMPLATEDESCRIPTION, ID_RIGHTS_MANAGEMENT_TEMPLATEDESCRIPTION)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_CONTENTOWNER, ID_RIGHTS_MANAGEMENT_CONTENTOWNER)
		result.AddTag(TAG_RIGHTS_MANAGEMENT_REMOVERIGHTSMANAGEMENTDISTRIBUTION, ID_RIGHTS_MANAGEMENT_REMOVERIGHTSMANAGEMENTDISTRIBUTION)
	}

	return result
}
