package codepages

import (
	. "github.com/magicmonty/activesync-go/activesync/base"
	"testing"
)

func Test_RightsManagement_120(t *testing.T) {
	cp := RightsManagement(PROTOCOL_VERSION_12_0)
	checkTagCount(t, 0, cp)
}

func Test_RightsManagement_121(t *testing.T) {
	cp := RightsManagement(PROTOCOL_VERSION_12_1)
	checkTagCount(t, 0, cp)
}

func Test_RightsManagement_140(t *testing.T) {
	cp := RightsManagement(PROTOCOL_VERSION_14_0)
	checkTagCount(t, 0, cp)
}

func Test_RightsManagement_141(t *testing.T) {
	cp := RightsManagement(PROTOCOL_VERSION_14_1)
	checkTagCount(t, 20, cp)

	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTSUPPORT, ID_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTSUPPORT, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTTEMPLATES, ID_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTTEMPLATES, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTTEMPLATE, ID_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTTEMPLATE, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTLICENSE, ID_RIGHTS_MANAGEMENT_RIGHTSMANAGEMENTLICENSE, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_EDITALLOWED, ID_RIGHTS_MANAGEMENT_EDITALLOWED, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_REPLYALLOWED, ID_RIGHTS_MANAGEMENT_REPLYALLOWED, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_REPLYALLALLOWED, ID_RIGHTS_MANAGEMENT_REPLYALLALLOWED, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_FORWARDALLOWED, ID_RIGHTS_MANAGEMENT_FORWARDALLOWED, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_MODIFYRECIPIENTSALLOWED, ID_RIGHTS_MANAGEMENT_MODIFYRECIPIENTSALLOWED, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_EXTRACTALLOWED, ID_RIGHTS_MANAGEMENT_EXTRACTALLOWED, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_PRINTALLOWED, ID_RIGHTS_MANAGEMENT_PRINTALLOWED, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_EXPORTALLOWED, ID_RIGHTS_MANAGEMENT_EXPORTALLOWED, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_PROGRAMMATICACCESSALLOWED, ID_RIGHTS_MANAGEMENT_PROGRAMMATICACCESSALLOWED, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_OWNER, ID_RIGHTS_MANAGEMENT_OWNER, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_CONTENTEXPIRYDATE, ID_RIGHTS_MANAGEMENT_CONTENTEXPIRYDATE, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_TEMPLATEID, ID_RIGHTS_MANAGEMENT_TEMPLATEID, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_TEMPLATENAME, ID_RIGHTS_MANAGEMENT_TEMPLATENAME, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_TEMPLATEDESCRIPTION, ID_RIGHTS_MANAGEMENT_TEMPLATEDESCRIPTION, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_CONTENTOWNER, ID_RIGHTS_MANAGEMENT_CONTENTOWNER, cp)
	checkTagExists(t, TAG_RIGHTS_MANAGEMENT_REMOVERIGHTSMANAGEMENTDISTRIBUTION, ID_RIGHTS_MANAGEMENT_REMOVERIGHTSMANAGEMENTDISTRIBUTION, cp)
}
